class { 'openshift_origin' :
  node_fqdn                  => "${hostname}.${domain}",
  cloud_domain               => 'example.com',
  dns_servers                => ['192.168.10.15'],
  os_unmanaged_users         => ['vagrant'],
  enable_network_services    => true,
  configure_firewall         => true,
  configure_ntp              => true,
  configure_activemq         => true,
  configure_qpid             => false,
  configure_mongodb          => true,
  configure_named            => false,
  configure_broker           => true,
  configure_node             => true,
  development_mode           => true,
  broker_auth_plugin         => 'kerberos',
  broker_dns_plugin          => 'nsupdate',
  #broker_dns_gsstsig         => true,
  #dns_kerberos_keytab        => '/etc/dns.keytab',
  #http_kerberos_keytab       => '/etc/http.keytab',
  kerberos_keytab            => '/etc/http.keytab',
  kerberos_realm             => 'EXAMPLE.COM',
  kerberos_service           => $::fqdn,
}
